#!/bin/bash

#Francis Paran
#file_tree

function argv() {
    if [ $1 -gt 0 ]; then
	    return 0
    else
	    return 1
    fi
}

show_hidden="0"
recurse="0"
line_by_line="0"
depth="0"

while getopts d:hlr OPTION ; do
	case $OPTION in
		d) # -d print files up to a certain depth
		    # in the tree
		    if [[ $OPTARG =~ [0-9] ]]
		    then
			    depth=$OPTARG
			    # echo "-d was triggered, Parameter: $OPTARG"
		    else
			    echo "-$OPTION: invalid argument value $OPTARG"
			    exit 1
		    fi;;
		:)
		    echo "Option -$OPTARG requires an argument."
		    exit 1;;
		h) # -h show hidden files
		    show_hidden="1" ;;
		l) # -l line by line
		    line_by_line="1" ;;
		r) # -r recursive
		    recurse="1" ;;
	       \?)
		    echo "Options: [-h (show hidden)], [-l (line by line)], [-r (recursive)] [<directory>||.]" 
		    exit 2 ;;
    	esac
done

shift $(($OPTIND-1))

if argv $#; then
	directory=${1}
else
	directory=`pwd`
fi	

# file_tree.py should be in the same directory as this file.                                     
# We use `which file_tree` here with the assumption that this script has
# been copied to a bin folder (preferably, /usr/local/bin).
python `which file_tree`.py "$directory" $show_hidden $recurse $depth $line_by_line

